### ISSUE TITLE
value error low >= high

### ISSUE THREAD

**Issue by DevaDinesh21** [includeamin/WBC-Classification#6]
File "test_model.py", line 75, in <module>
    idxs = np.random.randint(0, len(imagePaths), size=(10,))
  File "mtrand.pyx", line 630, in numpy.random.mtrand.RandomState.randint
  File "bounded_integers.pyx", line 1228, in numpy.random.bounded_integers._rand_int64
ValueError: low >= high

**Comment by includeamin** [comment]
#3

**Comment by DevaDinesh21** [comment]
once i skkiped that line 

ValueError: Error when checking input: expected conv2d_1_input to have 4 dimensions, but got array with shape (0, 1)
i got above error

**Comment by includeamin** [comment]
https://github.com/includeamin/WBC-Classification/issues/3#issuecomment-600572569  check it out
```
the dataset has three folders :
- TRAIN
- TEST
- TEST_SIMPLE

you should copy TEST folder to the dataset directory for testing
```

**Comment by includeamin** [comment]
### here is my current test:
![image](https://user-images.githubusercontent.com/11836741/76957771-103efa00-6934-11ea-8e62-218a4b10a77d.png)
### dataset directory:
![image](https://user-images.githubusercontent.com/11836741/76957994-7a579f00-6934-11ea-8112-598b8a5d2c40.png)

**Comment by naima-keb** [comment]
Can i exécuté this code in matlab or pycharm ?

**Comment by includeamin** [comment]
> Can i exécuté this code in matlab or pycharm ?
Hi do you read the [README](https://github.com/includeamin/WBC-Classification/blob/master/README.md)?
